import {test,expect,type Page} from '@playwright/test';
async function login(page:Page,role='mentor'){await page.goto('/');await page.getByLabel('Email',{exact:true}).fill(role+'@example.test');await page.getByLabel('Password',{exact:true}).fill('test-password');await page.getByRole('button',{name:'Sign In',exact:true}).click();await expect(page.getByRole('button',{name:'Inventory',exact:true})).toBeVisible();}
test('shared project movement updates balances and home audit via SQL RPC',async({page})=>{
 await login(page);await page.goto('/#locations');await page.getByRole('button',{name:'Add location',exact:true}).click();await page.getByLabel('Location name',{exact:true}).fill('Drivebase Prototype');await page.getByRole('button',{name:'Create location',exact:true}).click();await expect(page.getByRole('button',{name:/Drivebase Prototype/})).toBeVisible();
 await page.goto('/#inventory');await page.getByRole('button',{name:'Move 5/32" Allen wrench',exact:true}).click();await page.getByLabel('To location',{exact:true}).selectOption({label:'Drivebase Prototype'});await page.getByRole('button',{name:'Move inventory',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.goto('/#location/10000000-0000-4000-8000-000000000001');const row=page.locator('.audit-row').filter({has:page.getByRole('button',{name:'5/32" Allen wrench',exact:true})});await expect(row).toContainText('1 assigned elsewhere');await expect(row).toContainText('0 unaccounted');await page.getByRole('button',{name:'Mark drawer verified',exact:true}).click();await expect(page.getByRole('status')).toContainText('verified');
});
test('private photo upload, signed rendering, replacement and deletion use repository',async({page})=>{
 await login(page);await page.goto('/#inventory');await page.getByRole('button',{name:'5/32" Allen wrench',exact:true}).click();
 const png=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=2;c.height=2;const x=c.getContext('2d')!;x.fillStyle='green';x.fillRect(0,0,2,2);return c.toDataURL('image/png').split(',')[1];}),'base64');
 await page.getByLabel('Photo description').fill('SAE wrench reference');await page.getByLabel('Upload item photo').setInputFiles({name:'wrench.png',mimeType:'image/png',buffer:png});await expect(page.getByRole('dialog').getByAltText('SAE wrench reference')).toBeVisible();
 await page.getByLabel('Photo description').fill('Replacement wrench photo');await page.getByLabel('Upload item photo').setInputFiles({name:'updated.png',mimeType:'image/png',buffer:png});await expect(page.getByRole('dialog').getByAltText('Replacement wrench photo')).toBeVisible();
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 for(const width of [1440,1280,768,390]){await page.setViewportSize({width,height:900});await expect(page.getByAltText('Replacement wrench photo')).toBeVisible();await page.locator('.account-name').evaluate(el=>{el.textContent='Alexandria Longlastname — student.testing.account@school.example';});await page.locator('tbody .item-link').first().evaluate(el=>{el.textContent='5/32 inch Allen wrench — long handle mechanical assembly and maintenance tool';});expect(await page.getByAltText('Replacement wrench photo').evaluate(img=>img.getBoundingClientRect().width)).toBeGreaterThanOrEqual(48);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:`test-results/inventory-photos-${width}.png`,fullPage:true});}
 await page.goto('/#location/10000000-0000-4000-8000-000000000001');await page.getByLabel('Photo description').fill('TA-01 drawer reference');await page.getByLabel('Upload location photo').setInputFiles({name:'drawer.png',mimeType:'image/png',buffer:png});await expect(page.getByAltText('TA-01 drawer reference')).toBeVisible();await page.goto('/#locations');
 for(const width of [1440,1280,768,390]){await page.setViewportSize({width,height:900});await expect(page.getByAltText('TA-01 drawer reference')).toBeVisible();await page.locator('.location-card h2').first().evaluate(el=>{el.textContent='Toolbox A — Mechanical / General — shared school equipment and specialty tools';});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:`test-results/location-photos-${width}.png`,fullPage:true});}
 await page.goto('/#inventory');await page.getByRole('button',{name:'5/32" Allen wrench',exact:true}).click();
 await page.getByRole('button',{name:'Delete photo',exact:true}).click();await expect(page.locator('.photo-panel img')).toHaveCount(0);
});
test('student sees balance controls and cannot manage photos or create trips',async({page})=>{
 await login(page,'student');await page.goto('/#inventory');await page.getByRole('button',{name:'5/32" Allen wrench',exact:true}).click();await expect(page.getByLabel('Upload item photo')).toHaveCount(0);await expect(page.getByRole('button',{name:'Save count'}).first()).toBeEnabled();await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.goto('/#travel');await expect(page.getByRole('button',{name:'Create trip',exact:true})).toHaveCount(0);
});
