import {useEffect,useState,useRef,type ReactNode} from 'react';
import {ArrowRight,Camera,Plus,Package,Wrench,MapPin,BriefcaseBusiness,X} from 'lucide-react';
import {locationPath,ownerships,type Database,type Item} from './data';
import {inventoryRepository as repository} from './services/repository';
import {canCount,canEdit,isAdmin,type UserProfile} from './services/types';
import {atLocation,activeTrip,title,tripStatuses,type InventoryAction,type ActionData,type Media,type Manifest} from './services/logistics-model';
import {friendlyError} from './services/supabase';
export type RunAction=(action:InventoryAction|'enable',data:ActionData)=>Promise<boolean>;
const signed=new Map<string,{url:string;until:number}>();
export function Photo({photo,compact=false,alt='',location=false,itemType}:{photo?:Media;compact?:boolean;alt?:string;location?:boolean;itemType?:string}){
 const [url,setUrl]=useState(''),[failed,setFailed]=useState(false);
 useEffect(()=>{setUrl('');setFailed(false);if(!photo)return;let active=true;const load=async()=>{try{let cached=signed.get(photo.path);if(!cached||cached.until<Date.now()){cached={url:await repository.photoUrl(photo.path),until:Date.now()+3000000};signed.set(photo.path,cached);}if(active)setUrl(cached.url);}catch{if(active)setFailed(true);}};void load();const timer=setInterval(()=>void load(),3000000);return()=>{active=false;clearInterval(timer);};},[photo?.path]);
 const Icon=location?MapPin:itemType==='Tool'?Wrench:Package;
 return <span className={compact?'item-thumbnail':location?'location-photo-frame':'detail-photo-frame'}>{photo&&url&&!failed?<img src={url} alt={photo.alt||alt||'Inventory reference photo'} loading="lazy" decoding="async" onError={()=>setFailed(true)}/>:<span className="photo-placeholder" role="img" aria-label={`${alt||'Item'} — ${failed?'photo unavailable':'no photo'}`}><Icon size={compact?23:32}/></span>}</span>;
}
export function CreationModal({heading,close,children,busy=false}:{heading:string;close:()=>void;children:ReactNode;busy?:boolean}){
 const ref=useRef<HTMLElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector<HTMLInputElement>('input')?.focus();return()=>{document.body.style.overflow=overflow;previous?.focus();};},[]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)close();}} onKeyDown={e=>{if(e.key==='Escape'&&!busy){e.preventDefault();close();}if(e.key==='Tab'){const nodes=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')||[]);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><section ref={ref} className="modal creation-modal" role="dialog" aria-modal="true" aria-label={heading}><div className="modal-heading"><h2>{heading}</h2><button type="button" disabled={busy} className="icon-button" aria-label={`Close ${heading.toLowerCase()}`} onClick={close}><X/></button></div>{children}</section></div>;
}
export function NewTrip({run}:{run:RunAction}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <><button className="primary" onClick={()=>{setError('');setOpen(true);}}><Plus size={17}/>New trip</button>{open&&<CreationModal heading="New trip" busy={busy} close={()=>setOpen(false)}><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);if(await run('create_trip',Object.fromEntries(['name','event','destination','start','end','note'].map(k=>[k,String(f.get(k)||'').trim()]))))setOpen(false);else setError('Trip not created. Check the workspace error and try again.');setBusy(false);}}><div className="form-grid"><label>Trip name<input name="name" required pattern=".*\S.*" placeholder="2027 Denver Regional"/></label><label>Event<input name="event"/></label><label className="full">Destination<input name="destination"/></label><label>Start date<input name="start" type="date"/></label><label>End date<input name="end" type="date"/></label><label className="full">Trip notes<textarea name="note" rows={3}/></label></div>{error&&<p role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Creating…':'Create trip'}</button></div></form></CreationModal>}</>;
}
export function PhotoPanel({db,kind,id,editable,refresh}:{db:Database;kind:Media['entityType'];id:string;editable:boolean;refresh:()=>Promise<void>}){
 const photo=db.logistics?.media.find(p=>p.entityType===kind&&p.entityId===id);const [alt,setAlt]=useState(photo?.alt||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(!db.logistics)return null;
 return <section className="photo-panel">{photo&&<Photo photo={photo} alt={kind==='items'?db.items.find(i=>i.id===id)?.name:db.locations.find(l=>l.id===id)?.name}/>}{editable&&repository.mode==='supabase'&&<><label>Photo description<input value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Describe the tool or how to find this location"/></label><div className="button-row"><label className="secondary upload"><Camera size={16}/>{photo?'Replace photo':'Add photo'}<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" aria-label={`Upload ${kind==='items'?'item':'location'} photo`} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{await repository.savePhoto(kind,id,file,alt,photo);await refresh();}catch(e){setError(friendlyError(e));await refresh().catch(()=>{});}finally{setBusy(false);e.target.value='';}}}/></label>{photo&&<button type="button" className="text-button danger" disabled={busy} onClick={async()=>{setBusy(true);try{await repository.deletePhoto(photo);await refresh();}catch(e){setError(friendlyError(e));await refresh().catch(()=>{});}finally{setBusy(false);}}}>Delete photo</button>}</div><small>JPG, PNG or WebP · up to 5 MB · visible to signed-in teammates</small></>}{error&&<p role="alert">{error}</p>}</section>;
}
export function MovementHistory({db,itemId,tripId}:{db:Database;itemId?:string;tripId?:string}){
 const [names,setNames]=useState<Record<string,string>>({});useEffect(()=>{let active=true;void repository.profiles().then(p=>{if(active)setNames(Object.fromEntries(p.map(x=>[x.id,x.displayName||x.email])));}).catch(()=>{});return()=>{active=false;};},[]);
 const movements=[...(db.logistics?.movements??[])].filter(m=>(!itemId||m.itemId===itemId)&&(!tripId||m.tripId===tripId)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,30);
 return <section className="activity"><h2>Movement history</h2>{!movements.length&&<small>No movements recorded yet.</small>}{movements.map(m=><div key={m.id}><p><b>{names[m.userId]||'Team member'}</b> · {title(m.type)} · {m.quantity>0?`${m.quantity} ${m.itemName}`:m.itemName}</p>{(m.from||m.to)&&<small>{m.from?locationPath(db.locations,m.from):'Added'} → {m.to?locationPath(db.locations,m.to):'Removed'}</small>}{m.note&&<p>{m.note}</p>}<small>{new Date(m.createdAt).toLocaleString()}</small></div>)}</section>;
}
export function MoveDialog({db,item,run,close}:{db:Database;item:Item;run:RunAction;close:()=>void}){
 const balances=db.logistics!.balances.filter(b=>b.itemId===item.id&&b.quantity>0);const [from,setFrom]=useState(item.balanceLocationId||balances[0]?.locationId||item.locationId),[to,setTo]=useState(''),[qty,setQty]=useState('1'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const travel=db.locations.find(l=>l.id===from)?.tripId;
 return <div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="move-title" className="modal move-modal"><h2 id="move-title">Move {item.name}</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);if(await run('move',{itemId:item.id,from,to,quantity:Number(qty),note}))close();else setError('Move not saved. Review the error and current quantities.');setBusy(false);}}><div className="form-grid"><label>From location<select aria-label="From location" value={from} onChange={e=>setFrom(e.target.value)}>{balances.map(b=><option key={b.id} value={b.locationId}>{locationPath(db.locations,b.locationId)} — {b.quantity}</option>)}</select></label><label>To location<select aria-label="To location" required value={to} onChange={e=>setTo(e.target.value)}><option value="">Choose destination</option>{db.locations.filter(l=>l.active!==false&&!l.tripId&&l.id!==from).map(l=><option value={l.id} key={l.id}>{locationPath(db.locations,l.id)}</option>)}</select></label><label>Quantity to move<input type="number" min="0.001" step="any" max={balances.find(b=>b.locationId===from)?.quantity||0} required value={qty} onChange={e=>setQty(e.target.value)}/></label><label>Movement note<input value={note} onChange={e=>setNote(e.target.value)}/></label></div>{travel&&<p>Use this trip’s manifest to preserve the home allocation: <a href={`#trip/${travel}`} onClick={close}>Open trip</a></p>}{error&&<p role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy||!!travel||!balances.length}>Move inventory</button></div><small>Transfers change where stock is held, not the total owned.</small></form></section></div>;
}
export function ItemLocations({db,item,move,go,correct,verify}:{db:Database;item:Item;move?:()=>void;go:(path:string)=>void;correct?:(i:Item,q:number)=>Promise<boolean>;verify?:(i:Item)=>Promise<boolean>}){
 if(!db.logistics)return null;const current=db.items.find(i=>i.id===item.id)||item;
 return <section className="item-balances"><div className="panel-heading"><div><h2>Where they are</h2><p><b>{current.quantity} total tracked</b> · Target {current.target} overall</p><small>Expected {current.expectedQuantity??'not configured'} at home: {locationPath(db.locations,current.locationId)}</small></div>{move&&<button type="button" className="secondary" onClick={move}>Move</button>}</div>{db.logistics.balances.filter(b=>b.itemId===item.id&&(b.quantity>0||b.locationId===current.locationId)).map(b=>{const l=db.locations.find(l=>l.id===b.locationId);return <div className="balance-row" key={b.id}><button type="button" className="location-link" onClick={()=>go(`location/${b.locationId}`)}>{locationPath(db.locations,b.locationId)}</button><b>{b.quantity} here</b>{correct&&!l?.tripId&&<BalanceCorrection key={b.id+'-'+b.updatedAt} item={atLocation(db,current,b.locationId)} correct={correct} verify={verify}/>} {l?.tripId&&<button type="button" className="badge" onClick={()=>go(`trip/${l.tripId}`)}>Traveling · {db.logistics!.trips.find(t=>t.id===l.tripId)?.name}</button>}</div>})}<MovementHistory db={db} itemId={item.id}/></section>;
}
export function ProjectLocationForm({db,profile,run}:{db:Database;profile:UserProfile;run:RunAction}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(!db.logistics||(!isAdmin(profile)&&profile.role!=='lead'))return null;
 return <><button className="primary" onClick={()=>{setError('');setOpen(true);}}><Plus size={17}/>Add location</button>{open&&<CreationModal heading="Add location" busy={busy} close={()=>setOpen(false)}><form onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);if(await run('create_location',{name:String(d.get('name')).trim(),classification:String(d.get('classification')),areaId:String(d.get('area')),note:String(d.get('note'))}))setOpen(false);else setError('Location not created. Check the workspace error and try again.');setBusy(false);}}><div className="form-grid"><label>Location name<input required name="name" placeholder="Shooter Prototype"/></label><label>Classification<select name="classification">{(isAdmin(profile)?['project','robot','temporary','permanent','other']:['project']).map(k=><option value={k} key={k}>{title(k)}</option>)}</select></label><label>Owner area<select name="area">{db.areas.filter(a=>isAdmin(profile)||a.id===profile.primaryAreaId).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label className="full">Instructions<textarea name="note" rows={3}/></label></div>{error&&<p role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Creating…':'Create location'}</button></div></form></CreationModal>}</>;
}
export function Travel({db,profile,run,go,tripId,refresh}:{db:Database;profile:UserProfile;run:RunAction;go:(path:string)=>void;tripId?:string;refresh:()=>Promise<void>}){
 const [tab,setTab]=useState('Manifest'),[ownership,setOwnership]=useState(''),[operation,setOperation]=useState<{row:Manifest;action:'pack'|'internal'|'return'|'resolve'}|null>(null);
 if(!db.logistics)return <section className="panel settings-panel"><h2>Travel & movement</h2><p>{repository.mode==='demo'?'Enable a local movement demo to try balances and trips. Existing counts are preserved.':'A mentor needs to apply Supabase migrations 004 and 005, then reload this page. Existing inventory remains available.'}</p>{repository.mode==='demo'&&<button className="primary" onClick={()=>void run('enable',{})}>Enable movement demo</button>}</section>;
 const g=db.logistics,trip=g.trips.find(t=>t.id===tripId);const admin=isAdmin(profile),manager=admin||profile.role==='lead';
 if(!trip)return <>
  {!g.trips.length?<section className="panel travel-empty"><span className="travel-empty-icon"><BriefcaseBusiness size={32}/></span><h2>No trips yet</h2><p>Create a trip when the team is preparing for a regional, offseason event, or demo.</p>{admin?<NewTrip run={run}/>:<small>A mentor or admin can create the team’s next trip.</small>}</section>:['Active trips','Upcoming trips','Completed trips'].map((group,n)=>{const trips=g.trips.filter(t=>n===0?activeTrip(t)&&t.status!=='planning':n===1?t.status==='planning':!activeTrip(t));return trips.length>0&&<section className="travel-group" key={group}><h2>{group}</h2><div className="locations-grid">{trips.map(t=>{const m=g.manifest.filter(m=>m.tripId===t.id);const date=(value:string)=>value?new Date(value+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'';return <button className="panel trip-card" key={t.id} onClick={()=>go(`trip/${t.id}`)}><span className={`badge ${activeTrip(t)?'good':''}`}>{title(t.status)}</span><h3>{t.name}</h3><small>{t.start?`${date(t.start)}${t.end?' – '+date(t.end):''}`:'Dates to be confirmed'}</small><div className="trip-card-counts"><span>{new Set(m.map(x=>x.itemId)).size} manifest items</span><span>{m.filter(x=>x.status==='packed'&&x.ownership==='Shared / School').reduce((n,x)=>n+x.quantity,0)} school-owned units traveling</span><span>{m.filter(x=>x.status==='approved').reduce((n,x)=>n+x.quantity,0)} units still need packing</span></div><span className="trip-card-link">Open trip <ArrowRight size={16}/></span></button>})}</div></section>})}
 </>;
 const all=g.manifest.filter(m=>m.tripId===trip.id),manifest=all.filter(m=>!ownership||m.ownership===ownership);const tripLocations=db.locations.filter(l=>l.tripId===trip.id);const active=activeTrip(trip);
 return <><button className="text-button" onClick={()=>go('travel')}>All trips</button><section className="panel settings-panel"><div className="panel-heading"><div><h2>{trip.name}</h2><p>{trip.event} · {trip.destination} · {trip.start} {trip.end&&`— ${trip.end}`}</p></div>{admin&&active?<label>Trip status<select value={trip.status} onChange={e=>void run('trip_status',{tripId:trip.id,status:e.target.value})}>{tripStatuses.map(s=><option value={s} key={s}>{title(s)}</option>)}</select></label>:<span className="badge">{title(trip.status)}</span>}</div><p>{trip.notes}</p><div className="trip-tabs">{['Overview','Manifest','Locations','Activity','Return Audit'].map(t=><button className={tab===t?'primary':'secondary'} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div></section>
 {tab==='Overview'&&<section className="panel settings-panel"><h2>Trip overview</h2><p>{all.length} manifest allocations · {all.filter(m=>m.status==='packed').length} packed · {all.filter(m=>['approved','packed'].includes(m.status)).length} unresolved</p>{tripLocations.map(l=><p key={l.id}>{l.name}: {g.balances.filter(b=>b.locationId===l.id).reduce((n,b)=>n+b.quantity,0)} units here</p>)}</section>}
 {['Manifest','Return Audit'].includes(tab)&&<section className="panel settings-panel"><div className="panel-heading"><h2>{tab}</h2><label>Ownership<select aria-label="Filter trip ownership" value={ownership} onChange={e=>setOwnership(e.target.value)}><option value="">All ownership</option>{ownerships.map(o=><option key={o}>{o}</option>)}</select></label></div>
 {tab==='Return Audit'&&<div className="return-summary">{[...new Set(manifest.map(m=>m.itemId))].map(id=>{const rows=manifest.filter(m=>m.itemId===id),total=rows.reduce((n,m)=>n+m.quantity,0),returned=rows.filter(m=>m.status==='returned').reduce((n,m)=>n+m.quantity,0);return <p key={id}><b>{db.items.find(i=>i.id===id)?.name}</b> — {returned}/{total} returned · {rows.filter(m=>m.status==='packed').reduce((n,m)=>n+m.quantity,0)} still traveling · {rows.filter(m=>m.status==='resolved').reduce((n,m)=>n+m.quantity,0)} explicitly resolved</p>})}</div>}
 {!manifest.length&&<p>No manifest items yet.</p>}
 {manifest.map(m=>{const item=db.items.find(i=>i.id===m.itemId);return <div className="manifest-row" key={m.id}><div><b>{item?.name}</b><small>{m.quantity} · {m.ownership}</small><small>Home: {locationPath(db.locations,m.homeLocationId)}</small><small>{m.status==='approved'?'Pack to':'Current'}: {locationPath(db.locations,m.currentLocationId)}</small><span className={`badge ${m.status==='returned'?'good':''}`}>{title(m.status)}</span>{m.resolution&&<p>{m.resolution}</p>}</div><div className="button-row">{active&&canCount(profile)&&trip.status!=='planning'&&m.status==='approved'&&<button className="secondary" onClick={()=>setOperation({row:m,action:'pack'})}>Pack</button>}{active&&canCount(profile)&&m.status==='packed'&&<><button className="secondary" onClick={()=>setOperation({row:m,action:'internal'})}>Move within trip</button><button className="secondary" onClick={()=>setOperation({row:m,action:'return'})}>Return home</button></>}{active&&admin&&['approved','packed'].includes(m.status)&&<button className="text-button" onClick={()=>setOperation({row:m,action:'resolve'})}>Resolve</button>}</div></div>})}
 {active&&manager&&['planning','packing'].includes(trip.status)&&<ApproveForm db={db} tripId={trip.id} run={run}/>}</section>}
 {tab==='Locations'&&<div className="locations-grid">{tripLocations.map(l=><section className="panel settings-panel" key={l.id}><button className="item-link" onClick={()=>go(`location/${l.id}`)}>{l.name}</button><PhotoPanel db={db} kind="locations" id={l.id} editable={admin||canEdit(profile,l.areaId||'')} refresh={refresh}/></section>)}</div>}
 {tab==='Activity'&&<section className="panel settings-panel"><MovementHistory db={db} tripId={trip.id}/></section>}
 {operation&&<AllocationDialog key={operation.row.id+operation.action} db={db} {...operation} run={run} close={()=>setOperation(null)}/>}
 </>;
}
function ApproveForm({db,tripId,run}:{db:Database;tripId:string;run:RunAction}){
 const [itemId,setItem]=useState(db.items[0]?.id||'');const balances=db.logistics!.balances.filter(b=>b.itemId===itemId&&b.quantity>0&&!db.locations.find(l=>l.id===b.locationId)?.tripId);
 return <form className="form-grid approve-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await run('approve',{tripId,itemId,from:String(f.get('from')),to:String(f.get('to')),quantity:Number(f.get('quantity')),note:String(f.get('note'))});}}><h3 className="full">Add to trip / approve packing</h3><label>Manifest item<select value={itemId} onChange={e=>setItem(e.target.value)}>{db.items.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></label><label>Home / source<select name="from" required key={itemId}>{balances.map(b=><option value={b.locationId} key={b.id}>{locationPath(db.locations,b.locationId)} — {b.quantity}</option>)}</select></label><label>Initial travel location<select name="to" required>{db.locations.filter(l=>l.tripId===tripId&&l.parentId).map(l=><option value={l.id} key={l.id}>{locationPath(db.locations,l.id)}</option>)}</select></label><label>Approved quantity<input name="quantity" type="number" min="0.001" step="any" defaultValue="1" required/></label><label>Manifest note<input name="note"/></label><button className="primary" disabled={!balances.length}>Approve for packing</button><small className="full">Approval does not move stock. Students can pack approved quantities once the trip is Packing.</small></form>;
}
function AllocationDialog({db,row,action,run,close}:{db:Database;row:Manifest;action:'pack'|'internal'|'return'|'resolve';run:RunAction;close:()=>void}){
 const [busy,setBusy]=useState(false),[resolution,setResolution]=useState('lost'),[error,setError]=useState('');const item=db.items.find(i=>i.id===row.itemId);
 return <div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="allocation-title" className="modal move-modal"><h2 id="allocation-title">{title(action)} · {item?.name}</h2><p>Home: {locationPath(db.locations,row.homeLocationId)}</p><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);if(await run(action,{manifestId:row.id,quantity:Number(f.get('quantity')),to:String(f.get('to')||''),resolution,note:String(f.get('note')||'')}))close();else setError('Not saved. Review the current allocation and the error message.');setBusy(false);}}><label>Allocation quantity<input type="number" min="0.001" step="any" max={row.quantity} name="quantity" defaultValue={row.quantity} required/></label>{action==='resolve'&&<label>Resolution<select value={resolution} onChange={e=>setResolution(e.target.value)}><option value="lost">Lost / unaccounted</option><option value="consumed">Consumed</option><option value="transferred">Transferred elsewhere</option><option value="manual">Manually resolved at another location</option></select></label>}{(action==='internal'||action==='resolve'&&['transferred','manual'].includes(resolution))&&<label>Allocation destination<select name="to" required>{db.locations.filter(l=>l.active!==false&&l.id!==row.currentLocationId&&(action==='internal'?l.tripId===row.tripId:!l.tripId)).map(l=><option key={l.id} value={l.id}>{locationPath(db.locations,l.id)}</option>)}</select></label>}<label>Action note<input name="note" required={action==='resolve'}/></label>{action==='resolve'&&row.status==='approved'&&<p className="full">This resolves an unfilled approval; no inventory moves.</p>}{action==='resolve'&&row.status==='packed'&&<p className="full">Lost/consumed removes the selected units from tracked ownership. Other resolutions require their actual non-travel location. This is recorded in history.</p>}{error&&<p role="alert">{error}</p>}<div className="modal-actions full"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>Confirm {action}</button></div></form></section></div>;
}

function BalanceCorrection({item,correct,verify}:{item:Item;correct:(i:Item,q:number)=>Promise<boolean>;verify?: (i:Item)=>Promise<boolean>}){
 const [quantity,setQuantity]=useState(String(item.quantity)),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <div className="balance-correction"><input aria-label={`Count at ${item.locationId}`} type="number" min="0" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)}/><button type="button" className="text-button" disabled={busy||quantity===''||!Number.isFinite(Number(quantity))||Number(quantity)<0} onClick={async()=>{setBusy(true);const ok=await correct(item,Number(quantity));setMessage(ok?'Count saved':'Count not saved');setBusy(false);}}>Save count</button>{verify&&<button type="button" className="text-button" disabled={busy||Number(quantity)!==item.quantity} onClick={async()=>{setBusy(true);const ok=await verify(item);setMessage(ok?'Location count verified':'Verification not saved');setBusy(false);}}>Verify quantity</button>}{message&&<small role="status">{message}</small>}</div>;
}
